use_frameworks!

platform :ios, '10.0'

target 'iMengqingTest_Example' do
  pod 'iMengqingTest', :path => '../'

  target 'iMengqingTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
